#
# Copyright TRIDENT-ARTS All Rights Reserved
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Ordering peer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: trident-arts.net
    Specs:
      - Hostname: orderer
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:              
  - Name: Tadev organization
    Domain: org1.trident-arts.net
    Template:
      Count: 2
    Users:
      Count: 1
