#
# Copyright TRIDENT-ARTS All Rights Reserved
#
#
version: '2'

networks:
  basic:

services:

  ca.trident-arts.net:
    image: hyperledger/fabric-ca:x86_64-1.0.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.trident-arts.net
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.trident-arts.net-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/f18b315683e34721aba22bbcbf9efe026c90e1157334a12c3e78653d0d16a5e4_sk
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.trident-arts.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.trident-arts.net
    networks:
      - basic

  orderer.trident-arts.net:
    container_name: orderer.trident-arts.net
    image: hyperledger/fabric-orderer:x86_64-1.0.5
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
      - ./config/:/etc/hyperledger/configtx
      - ./crypto-config/ordererOrganizations/trident-arts.net/orderers/orderer.trident-arts.net/:/etc/hyperledger/msp/orderer
      - ./crypto-config/peerOrganizations/org1.trident-arts.net/peers/peer0.org1.trident-arts.net/:/etc/hyperledger/msp/peer0Org1
      - ./crypto-config/peerOrganizations/org1.trident-arts.net/peers/peer1.org1.trident-arts.net/:/etc/hyperledger/msp/peer1Org1
    networks:
      - basic

  peer0.org1.trident-arts.net:
    container_name: peer0.org1.trident-arts.net
    extends:
      file: peer-base.yaml
      service: peer-base        
    environment:      
      - CORE_PEER_ID=peer0.org1.trident-arts.net
      - CORE_PEER_ADDRESS=peer0.org1.trident-arts.net:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.trident-arts.net:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.trident-arts.net:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.trident-arts.net/users/Admin@org1.trident-arts.net/msp
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.trident-arts.net/peers/peer0.org1.trident-arts.net/msp:/etc/hyperledger/msp/peer        
      - ./crypto-config/peerOrganizations/org1.trident-arts.net/users:/etc/hyperledger/msp/users
      - ./config:/etc/hyperledger/configtx
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    depends_on:
      - orderer.trident-arts.net
    networks:
      - basic

  peer1.org1.trident-arts.net:
    container_name: peer1.org1.trident-arts.net
    extends:
      file:  peer-base.yaml
      service: peer-base
    environment:      
      - CORE_PEER_ID=peer1.org1.trident-arts.net
      - CORE_PEER_ADDRESS=peer1.org1.trident-arts.net:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.trident-arts.net:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.trident-arts.net:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.trident-arts.net/users/Admin@org1.trident-arts.net/msp
    ports:
      - 8051:7051
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.trident-arts.net/peers/peer1.org1.trident-arts.net/msp:/etc/hyperledger/msp/peer        
      - ./crypto-config/peerOrganizations/org1.trident-arts.net/users:/etc/hyperledger/msp/users
      - ./config:/etc/hyperledger/configtx
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    depends_on:
      - orderer.trident-arts.net
    networks:
      - basic

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:x86_64-1.0.5
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.trident-arts.net:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.trident-arts.net/users/Admin@org1.trident-arts.net/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    volumes:
        - ./config:/etc/hyperledger/configtx
        - /var/run/:/host/var/run/        
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./chaincode/:/opt/gopath/src/github.com/                
    depends_on:
      - orderer.trident-arts.net
      - peer0.org1.trident-arts.net
      - peer1.org1.trident-arts.net
    networks:
      - basic